name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Docker build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      - name: Build the Docker image
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build the Docker image
        run: docker build  --platform linux --tag ${{ secrets.DOCKERHUB_USERNAME }}/backenddockerci:latest -f docker_devops_git/docker_master/CI/dockerfile docker_devops_git/docker_master/CI/
      - name: Push the Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/backenddockerci:latest
